CREATE DATABASE Ado_net;

USE Ado_net;

CREATE TABLE Countries(
	Id INT PRIMARY KEY IDENTITY(1, 1),
	[Name] NVARCHAR(50) NOT NULL,
	Area DECIMAL(15, 2) NOT NULL,
	[Population] INT
);

CREATE TABLE Cities(
	Id INT PRIMARY KEY IDENTITY(1, 1),
	[Name] NVARCHAR(50) NOT NULL,
	Area DECIMAL(15, 2) NOT NULL,
	CountryId INT NOT NULL,
	FOREIGN KEY (CountryId) REFERENCES Countries(Id) ON DELETE CASCADE
);